### ISSUE TITLE
Loading QR Code viewer in a container

### ISSUE THREAD

**Issue by sbesh91** [bcko/flutter_qrcode_reader#10]
The Current implementation doesn't provide a hook to embed the QR Code scanner into a container widget.

**Comment by haarts** [comment]
What would be needed to implement this? I would really like to embed the reader into my widget tree instead of using a totally different view/overlay.

**Comment by facundomedica** [comment]
Hello, I had the same need so I went and wrote my own library, feedback is welcomed! https://github.com/facundomedica/fast_qr_reader_view

**Comment by haarts** [comment]
That is good to hear! Why is the Firebase registration necessary?

**Comment by facundomedica** [comment]
@haarts it's because it uses ML Kit from them. You usually use it for push notifications, so it's more or less standard. Anyway, open an issue so we can discuss this! 😄
