### ISSUE TITLE
Error building project

### ISSUE THREAD

**Issue by f1010** [bcko/flutter_qrcode_reader#11]
```
[public class QRCodeReaderPlugin implements MethodCallHandler, ActivityResultListener, PluginRegistry.RequestPermissionResultListener {
                                                                                                    ^
  symbol:   class RequestPermissionResultListener
  location: interface PluginRegistry
C:\..\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\qrcode_reader-0.3.2\android\src\main\java\com\matheusvillela\flutter\plugins\qrcodereader\QRCodeReaderPlugin.java:63: error: cannot find symbol
            registrar.addRequestPermissionResultListener(instance);
                     ^
  symbol:   method addRequestPermissionResultListener(QRCodeReaderPlugin)
  location: variable registrar of type Registrar](url)
```
```
error: method does not override or implement a method from a supertype
    @Override
    ^
```

**Comment by villela** [comment]
https://docs.flutter.io/javadoc/io/flutter/plugin/common/PluginRegistry.Registrar.html

addRequestPermissionResultListener(PluginRegistry.RequestPermissionResultListener listener)
Deprecated.  on 2018-01-02 because of misspelling

Not sure why they changed names and removed it in 4 weeks. The whole class is misspelled, "registrar" is "register" in portuguese.

**Comment by villela** [comment]
https://github.com/villela/flutter_qrcode_reader/commit/7e003ebb45d30bff753198f172474165ccb844fe

**Comment by sanattaori** [comment]
Project build failed error not resolved

**Comment by sanattaori** [comment]
Please fix error `C:\Users\Sanat\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\qrcode_reader-0.3.2\android\src\main\java\com\matheusvillela\flutter\plugins\qrcodereader\QRCodeReaderPlugin.java:42:` error: cannot find symbol
public class QRCodeReaderPlugin implements MethodCallHandler, ActivityResultListener, PluginRegistry.RequestPermissionResultListener {
                                                                                                    ^
  symbol:   class RequestPermissionResultListener
  location: interface PluginRegistry
C:\Users\Sanat\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\qrcode_reader-0.3.2\android\src\main\java\com\matheusvillela\flutter\plugins\qrcodereader\QRCodeReaderPlugin.java:63: error: cannot find symbol
            registrar.addRequestPermissionResultListener(instance);
                     ^
  symbol:   method addRequestPermissionResultListener(QRCodeReaderPlugin)
  location: variable registrar of type Registrar
C:\Users\Sanat\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\qrcode_reader-0.3.2\android\src\main\java\com\matheusvillela\flutter\plugins\qrcodereader\QRCodeReaderPlugin.java:155: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: C:\Users\Sanat\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\qrcode_reader-0.3.2\android\src\main\java\com\matheusvillela\flutter\plugins\qrcodereader\QRCodeReaderPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':qrcode_reader:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 55s
Finished with error: Gradle build failed: 1
```

**Comment by f1010** [comment]
Yes right, error not resolved.

**Comment by villela** [comment]
Ohhh sorry about that, it wasn't the only problem them.

I've tried to update my flutter installation, reinstalling etc but even if the flutter doctor says it's all ok I can't build the project.

I'll be closing this project, Flutter just doesn't work.

**Comment by tamcy** [comment]
Oh please don't. I have submitted a pull request (https://github.com/bcko/flutter_qrcode_reader/pull/12) which should fix this issue. Thanks for the work.

**Comment by bcko** [comment]
#12 merged
