### ISSUE TITLE
Unhandled exception: MissingPluginException(No implementation found for method readQRCode on channel qrcode_reader)

### ISSUE THREAD

**Issue by dixonl90** [bcko/flutter_qrcode_reader#21]
Hello,

I've been running the library in an app on my Nexus 6 and it has been working fine, except for once when it gave me the following error:

`08-10 14:52:36.099 18253-18471/com.londonsockcompany.sockspotter E/flutter: [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
    MissingPluginException(No implementation found for method readQRCode on channel qrcode_reader)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
    <asynchronous suspension>
    #1      QRCodeReader.scan (package:qrcode_reader/QRCodeReader.dart:67:27)
    <asynchronous suspension>
    #2      CorrectSockState.build.<anonymous closure> (package:sock_spotter/components/correct_sock.dart:54:30)
    #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
    #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
    #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
    #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
    #7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
    #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
    #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
    #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
    #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
    #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
    #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
    #14     _invoke1 (dart:ui/hooks.dart:134:13)
    #15     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)`

It happened in the middle of a presentation (never do a live demo!) but hasn't occurred since. Any idea what happened? Can I provide any more debug info? It has been working fine on a Pixel XL and iPhone X.

Thanks

**Comment by didyqian** [comment]
I got the same problem

**Comment by bjoernQ** [comment]
Happens to me as well on Android when I leave the app via pressing back until the Activity gets closed.
Reopening the app tries to re-register the plugins but this

https://github.com/bcko/flutter_qrcode_reader/blob/master/android/src/main/java/com/matheusvillela/flutter/plugins/qrcodereader/QRCodeReaderPlugin.java#L59

will prevent the plugin from registering again when instance is != null

**Comment by johanhenselmans** [comment]
Have a look at the branch android_fix. Try that one, and see if it helps. I tried it on a Android7 device, did not seem to have any side effects.

**Comment by bjoernQ** [comment]
the change looks good - I'll give it a try. Just need to figure out how to use a local copy of a plugin in Flutter (I'm new to Flutter)

**Comment by johanhenselmans** [comment]
See https://www.dartlang.org/tools/pub/dependencies, 
What you want in pubspec.yaml is 
qrcode_reader:
    git: 
https://github.com/bcko/flutter_qrcode_reader.git

**Comment by bjoernQ** [comment]
@johanhenselmans your fix seems to work fine for us - thanks

**Comment by dumpcoder** [comment]
@johanhenselmans This worked perfectly!

**Comment by liuyuejiang** [comment]
flutter clean and re-debug again

**Comment by java-james** [comment]
@johanhenselmans Thanks 

Can we get this merged ??
