### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by tamcy** [bcko/flutter_qrcode_reader#26]
Currently there're two variants of the QRCode Reader project:
1. https://github.com/bcko/flutter_qrcode_reader, corresponds to https://pub.dartlang.org/packages/qrcode_reader
2. https://github.com/PonnamKarthik/QRCodeReaderFlutter, corresponds to  https://pub.dartlang.org/packages/qr_reader
(Difference is `qrcode` vs `qr` in the Pub package name.)

Looks like the background story is this:
1. @villela started the project originally. (https://github.com/villela/flutter_qrcode_reader)
2. At some point it's no longer maintained.
3. @PonnamKarthik started a fresh repo by copying the project (not forking) and add update.
4. @villela's project transferred to @bcko

And the current status is like this:
1. @bcko's version keeps project history, continue accepting pull requests, but no new version is published on Pub.
2. @PonnamKarthik's version doesn't keep project history, contains different fixes (mainly by the author himself), have a Dart 2 compatible version published on Pub.

Obviously two diverged versions of the same project isn't the best for the project maintainers, the users and the potential contributers. So before both go too far away I have two suggestions here:
1. Obsolete one of the project. If @PonnamKarthik agree, I'd suggest to continue working on @bcko's version (as it keeps a more complete commit history), merge patches from @PonnamKarthik, publish a new version, and obsolete @PonnamKarthik's one. (I don't know, is it possible for @bcko grant the right to someone else to publish new version on pub?)
2. Evaluate if there's a more active project working on similar features, and ask people to focus the contribution effort to that project. This is of course said, but might be the best solution if the authors of the two projects are too busy to keep the projects maintained.

These are just my uninformed opinions, I really don't know the status of both authors. In closing, I'd like to thank @bcko and @PonnamKarthik for your effort on the project.

**Comment by tamcy** [comment]
@bcko Don't say that 😀. This is fully understandable - actually I discovered this two weeks ago and didn't get the time to write up until yesterday. 

I never used pub, but it looks it's possible to [transfer the owner of a library to someone else](https://stackoverflow.com/questions/20786435/transferring-a-dart-library-to-another-owner-in-pub-dartlang-org). Surely this needs help from @villela. Not sure if @-ing him will send him a notification. Otherwise I may open an issue in one of his project to draw his attention.

**Comment by villela** [comment]
Hello.

Make an account and I'll give @bcko the ownership of the pub sub

**Comment by bcko** [comment]
Hello, @villela 

my gmail address is gobcko@gmail.com. (https://www.dartlang.org/tools/pub/cmd/pub-uploader)
Thank you!

**Comment by villela** [comment]
Done @bcko! Tell me if it's working.

**Comment by bcko** [comment]
I am really sorry for the delay. I was hoping to work on this last weekend but couldn't due to startup and family. Is it ok for maybe have @PonnamKarthik and @tamcy to also get ownership of the pub sub so they can also publish the update? Again I am really sorry.

**Comment by suparnavg** [comment]
@bcko thanks so much for taking ownership on this! I was wondering if you got a chance to publish the update? Facing the compatibility issue..

"Because xyz depends on qrcode_reader >=0.1.1 which requires SDK version >=1.8.0 <2.0.0, version solving failed."

**Comment by bcko** [comment]
published the update :)
