### ISSUE TITLE
Can't install it  for dart sdk 2.1

### ISSUE THREAD

**Issue by mbdax034** [bcko/flutter_qrcode_reader#29]
Hello
I get this error frop pubspec:

The current Dart SDK version is 2.1.0-dev.5.0.flutter-a2eb050044.

depends on qrcode_reader >=0.1.1 which requires SDK version >=1.8.0 <2.0.0, 
version solving failed.

**Comment by suparnavg** [comment]
@mbdax034 did you manage to figure this one out? I'm facing the same issue..

**Comment by bcko** [comment]
package updated
