### ISSUE TITLE
Issue with QR CODE when using it second time

### ISSUE THREAD

**Issue by mohdyasar** [bcko/flutter_qrcode_reader#30]
I am using this plugin

First time while using the app the QR Code works fine, but when i minimize the app i.e. when its running in the background, then i come back again and try to use, its giving the following error.

It is working on IOS but not working on Android, 

Detailed error below

E/flutter ( 4790): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 4790): MissingPluginException(No implementation found for method readQRCode on channel qrcode_reader)
E/flutter ( 4790): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:291:7)
E/flutter ( 4790): <asynchronous suspension>
E/flutter ( 4790): #1      QRCodeReader.scan (package:qrcode_reader/qrcode_reader.dart:67:27) 

please can someone assist on this

thanks

**Comment by didyqian** [comment]
I got the same problem

**Comment by johanhenselmans** [comment]
Could you try the android_fix branch? I am not too sure about the fix, but I did not encounter any plugin that worked the way this android plugin worked, so I tweaked it a littl.
