### ISSUE TITLE
Half the screen goes white when holding the phone horizontally

### ISSUE THREAD

**Issue by mploigt** [bcko/flutter_qrcode_reader#36]
When you hold the phone (in this case an iPhone X) horizontally, the view switches to a new layout. where only the top half of the screen is the camera, the bottom half is white. You can only see the "Ca" of the "Cancel" button on the right side of the screen. Example: https://www.dropbox.com/s/0603ajyixd9jxpp/tiltBug.mov?dl=0

**Comment by cah4a** [comment]
Same issue.

I've found that after rotation `[[UIDevice currentDevice] orientation]` returns strange values, that not depends on device orientation settings. In my app orientation was locked but currentDevice orientation still changes.

I don't understand what's going on here, i am not an ios developer.

But) I stackoverflow it, and made a fix using `[UIApplication sharedApplication].statusBarOrientation` which is a common approach.

**Comment by oldmilk** [comment]
May I have this latest version available on https://pub.dev/ ?
